sdhdevicetype: ESD
sdhdevicestring: /dev/can0
dsadevicestring: /dev/ttyS0
baudrate: 500000 
joint_names: ['sdh_knuckle_joint', 'sdh_thumb_2_joint', 'sdh_thumb_3_joint', 'sdh_finger_12_joint', 'sdh_finger_13_joint', 'sdh_finger_22_joint', 'sdh_finger_23_joint']
OperationMode: position
frequency: 5
