left_arm_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - left_arm_7_joint

right_arm_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
    - right_arm_7_joint

gripper_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - left_arm_top_finger_joint
    - left_arm_bottom_finger_joint